
package com.example.agent.demoModel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DemoServicePortService", targetNamespace = "http://techprimers.com/demo", wsdlLocation = "http://localhost:8080/soapWS/entiteti.wsdl")
public class DemoServicePortService
    extends Service
{

    private final static URL DEMOSERVICEPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEMOSERVICEPORTSERVICE_EXCEPTION;
    private final static QName DEMOSERVICEPORTSERVICE_QNAME = new QName("http://techprimers.com/demo", "DemoServicePortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/soapWS/entiteti.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEMOSERVICEPORTSERVICE_WSDL_LOCATION = url;
        DEMOSERVICEPORTSERVICE_EXCEPTION = e;
    }

    public DemoServicePortService() {
        super(__getWsdlLocation(), DEMOSERVICEPORTSERVICE_QNAME);
    }

    public DemoServicePortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEMOSERVICEPORTSERVICE_QNAME, features);
    }

    public DemoServicePortService(URL wsdlLocation) {
        super(wsdlLocation, DEMOSERVICEPORTSERVICE_QNAME);
    }

    public DemoServicePortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEMOSERVICEPORTSERVICE_QNAME, features);
    }

    public DemoServicePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoServicePortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DemoServicePort
     */
    @WebEndpoint(name = "DemoServicePortSoap11")
    public DemoServicePort getDemoServicePortSoap11() {
        return super.getPort(new QName("http://techprimers.com/demo", "DemoServicePortSoap11"), DemoServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DemoServicePort
     */
    @WebEndpoint(name = "DemoServicePortSoap11")
    public DemoServicePort getDemoServicePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://techprimers.com/demo", "DemoServicePortSoap11"), DemoServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEMOSERVICEPORTSERVICE_EXCEPTION!= null) {
            throw DEMOSERVICEPORTSERVICE_EXCEPTION;
        }
        return DEMOSERVICEPORTSERVICE_WSDL_LOCATION;
    }

}
