
package com.example.agent.demoModel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DemoServicePort", targetNamespace = "http://techprimers.com/demo")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DemoServicePort {


    /**
     * 
     * @param getUserCredentialRequest
     * @return
     *     returns com.techprimers.demo.GetUserCredentialResponse
     */
    @WebMethod
    @WebResult(name = "getUserCredentialResponse", targetNamespace = "http://techprimers.com/demo", partName = "getUserCredentialResponse")
    public GetUserCredentialResponse getUserCredential(
        @WebParam(name = "getUserCredentialRequest", targetNamespace = "http://techprimers.com/demo", partName = "getUserCredentialRequest")
        GetUserCredentialRequest getUserCredentialRequest);

    /**
     * 
     * @param addSmestajRequest
     * @return
     *     returns com.techprimers.demo.AddSmestajResponse
     */
    @WebMethod
    @WebResult(name = "addSmestajResponse", targetNamespace = "http://techprimers.com/demo", partName = "addSmestajResponse")
    public AddSmestajResponse addSmestaj(
        @WebParam(name = "addSmestajRequest", targetNamespace = "http://techprimers.com/demo", partName = "addSmestajRequest")
        AddSmestajRequest addSmestajRequest);

}
