//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.22 at 12:05:56 AM CEST 
//


package com.example.agent.entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for realizacija.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="realizacija">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="REALIZED"/>
 *     &lt;enumeration value="UNREALIZED"/>
 *     &lt;enumeration value="WAITING_TO_CHECK_IN"/>
 *     &lt;enumeration value="WAITING_TO_CONFIRM_REALIZATION"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "realizacija")
@XmlEnum
public enum Realizacija {

    REALIZED,
    UNREALIZED,
    WAITING_TO_CHECK_IN,
    WAITING_TO_CONFIRM_REALIZATION;

    public String value() {
        return name();
    }

    public static Realizacija fromValue(String v) {
        return valueOf(v);
    }

}
