//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.22 at 12:05:56 AM CEST 
//


package com.example.agent.entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tip.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tip">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HOTEL"/>
 *     &lt;enumeration value="BED_BREAKFAST"/>
 *     &lt;enumeration value="APARTMENT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tip")
@XmlEnum
public enum Tip {

    HOTEL,
    BED_BREAKFAST,
    APARTMENT;

    public String value() {
        return name();
    }

    public static Tip fromValue(String v) {
        return valueOf(v);
    }

}
