//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.14 at 02:42:35 PM CEST 
//


package com.example.demo.entities;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}rezervacija"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id_smestaja" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="broj" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="kapacitet" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="cena" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rezervacija"
})
@XmlRootElement(name = "soba")
@Document(collection="Sobe")
public class Soba {

	protected List<Rezervacija> rezervacije;
    
    @Id
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "id_smestaja")
    protected String idSmestaja;
    @XmlAttribute(name = "broj")
    protected Integer broj;
    @XmlAttribute(name = "kapacitet")
    protected Integer kapacitet;
    @XmlAttribute(name = "cena")
    protected Integer cena;

    /**
     * Gets the value of the datumiRezervacija property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datumiRezervacija property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatumiRezervacija().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<Rezervacija> getRezervacije() {
        if (rezervacije == null) {
        	rezervacije = new ArrayList<Rezervacija>();
        }
        return this.rezervacije;
    }
    
    
    public void setRezervacije(List<Rezervacija> rezervacije) {
		this.rezervacije = rezervacije;
	}



	/**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }
    
      

	/**
     * Gets the value of the id_smestaja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdSmestaja() {
		return idSmestaja;
	}


    /**
     * Sets the value of the id_smestaja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
	public void setIdSmestaja(String idSmestaja) {
		this.idSmestaja = idSmestaja;
	}


	/**
     * Gets the value of the broj property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBroj() {
        return broj;
    }

    /**
     * Sets the value of the broj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBroj(Integer value) {
        this.broj = value;
    }

    /**
     * Gets the value of the kapacitet property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getKapacitet() {
        return kapacitet;
    }

    /**
     * Sets the value of the kapacitet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setKapacitet(Integer value) {
        this.kapacitet = value;
    }

    /**
     * Gets the value of the cena property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCena() {
        return cena;
    }

    /**
     * Sets the value of the cena property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCena(Integer value) {
        this.cena = value;
    }


    
    
	public Soba() {
		super();
		// TODO Auto-generated constructor stub
	}


	public Soba(List<Rezervacija> rezervacije, String idSmestaja, Integer broj, Integer kapacitet, Integer cena) {
		super();
		this.rezervacije = rezervacije;
		this.idSmestaja = idSmestaja;
		this.broj = broj;
		this.kapacitet = kapacitet;
		this.cena = cena;
	}
    
    

}
