
package com.example.demo.agentskiModel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SmestajServicePort", targetNamespace = "http://www.w3.org/2001/XMLSchema/agent")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SmestajServicePort {


    /**
     * 
     * @param addMessageRequest
     * @return
     *     returns org.w3._2001.xmlschema.agent.AddMessageResponse
     */
    @WebMethod
    @WebResult(name = "addMessageResponse", targetNamespace = "http://www.w3.org/2001/XMLSchema/agent", partName = "addMessageResponse")
    public AddMessageResponse addMessage(
        @WebParam(name = "addMessageRequest", targetNamespace = "http://www.w3.org/2001/XMLSchema/agent", partName = "addMessageRequest")
        AddMessageRequest addMessageRequest);

    /**
     * 
     * @param getSmestajRequest
     * @return
     *     returns org.w3._2001.xmlschema.agent.GetSmestajResponse
     */
    @WebMethod
    @WebResult(name = "getSmestajResponse", targetNamespace = "http://www.w3.org/2001/XMLSchema/agent", partName = "getSmestajResponse")
    public GetSmestajResponse getSmestaj(
        @WebParam(name = "getSmestajRequest", targetNamespace = "http://www.w3.org/2001/XMLSchema/agent", partName = "getSmestajRequest")
        GetSmestajRequest getSmestajRequest);

}
