
package com.example.demo.agentskiModel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SmestajServicePortService", targetNamespace = "http://www.w3.org/2001/XMLSchema/agent", wsdlLocation = "http://localhost:8081/soapWS/entiteti.wsdl")
public class SmestajServicePortService
    extends Service
{

    private final static URL SMESTAJSERVICEPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SMESTAJSERVICEPORTSERVICE_EXCEPTION;
    private final static QName SMESTAJSERVICEPORTSERVICE_QNAME = new QName("http://www.w3.org/2001/XMLSchema/agent", "SmestajServicePortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/soapWS/entiteti.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMESTAJSERVICEPORTSERVICE_WSDL_LOCATION = url;
        SMESTAJSERVICEPORTSERVICE_EXCEPTION = e;
    }

    public SmestajServicePortService() {
        super(__getWsdlLocation(), SMESTAJSERVICEPORTSERVICE_QNAME);
    }

    public SmestajServicePortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMESTAJSERVICEPORTSERVICE_QNAME, features);
    }

    public SmestajServicePortService(URL wsdlLocation) {
        super(wsdlLocation, SMESTAJSERVICEPORTSERVICE_QNAME);
    }

    public SmestajServicePortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMESTAJSERVICEPORTSERVICE_QNAME, features);
    }

    public SmestajServicePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmestajServicePortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SmestajServicePort
     */
    @WebEndpoint(name = "SmestajServicePortSoap11")
    public SmestajServicePort getSmestajServicePortSoap11() {
        return super.getPort(new QName("http://www.w3.org/2001/XMLSchema/agent", "SmestajServicePortSoap11"), SmestajServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmestajServicePort
     */
    @WebEndpoint(name = "SmestajServicePortSoap11")
    public SmestajServicePort getSmestajServicePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.w3.org/2001/XMLSchema/agent", "SmestajServicePortSoap11"), SmestajServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMESTAJSERVICEPORTSERVICE_EXCEPTION!= null) {
            throw SMESTAJSERVICEPORTSERVICE_EXCEPTION;
        }
        return SMESTAJSERVICEPORTSERVICE_WSDL_LOCATION;
    }

}
